### ISSUE TITLE
Newline at the end of a quoted printable body

### ISSUE THREAD

**Issue by lyrm** [mirage/mrmime#74]
Hi, 
Some of the parsed mails are different from the generated ones by only one char: a newline char (```=0A```) has been added at the very end of the body . Is it an expected behaviour ?

Some seeds with this issue : 34, 299 and 421.

**Comment by dinosaure** [comment]
> Some of the parsed mails are different from the generated ones by only one char: a newline char (=0A) has been added at the very end of the body . Is it an expected behaviour ?

I noticed already such behavior and I'm not sure that it's expected or not. However, the issue is more about `pecu` than `mrmime`. Due to the release of `pecu.0.4`, the best will be to add _by hands_ this new line (it seems that it appears for any quoted-printable contents). Then, we will try to find the bug according to RFC 2045.

**Comment by lyrm** [comment]
I tried adding a `\n` at the end of any generated quoted printable body but another one is added anyway.

**Comment by dinosaure** [comment]
To explain a bit the situation and according to an old version of me:
https://github.com/mirage/mrmime/blob/d707c75a0ffb9cd0b8d8e8a47d367853f83ce374/lib/mt.ml#L32-L39

Such behavior is expected to ensure that `mrmime` always emits lines even if the user don't want to encode a quoted-printable contents with a new line. By this way, `mrmime` is easily pluggable to `colombe` without a _proxy_. Such execution path does not strictly respect our expected isomorphism but it deals well with the end-user. Considering that it's fine - however, we should describe such behavior into the documentation.
